apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: webapp
  template:
    metadata:
      labels:
        pod: webapp
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: node
                operator: In
                values:
                - kmaster1
      containers:
      - name: webapp
        image: webapp
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "python3 manage.py makemigrations; python3 manage.py migrate; python3 manage.py runserver 0.0.0.0:8080"]
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_HOST
          value: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    pod: webapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 8080
  type: NodePort

